spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/course}
spring.datasource.username=${DB_USER:course}
spring.datasource.password=${DB_PASSWORD:course}
spring.jpa.hibernate.ddl-auto=validate
